### ISSUE TITLE
Highlighting in thread watcher when replied to

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#43]
Since v1.9.8.0 4chan X highlights threads in the thread watcher with unread posts quoting you by adding the `replies-quoting-you` class.  For this feature to work for Oneechan users, some CSS will need to be added for this class.

**Comment by nebukazar** [comment]
Thank you I overlooked that. 

I will likely add more color classes since 4chan X has gotten so many new options and having everything tied to just `highlightColor` doesn't give that much control. You also have some weird stuff like your posts/posts replying to you using `tripColor` instead of `highlightColor` but that's what looked best at the time and it still looks okay in my opinion but it's confusing for people who don't know the inner workings.

**Comment by ccd0** [comment]
On a related note, I'm adding similar highlighting to the shortcut/icon: 
https://github.com/ccd0/4chan-x/commit/9737cb47d55d1f1b0d29f1e2bf425e779097ef30

**Comment by nebukazar** [comment]
Neat.

I had to work around your !important by being more specific in the CSS, but it works.

**Comment by ccd0** [comment]
Unfortunately there are some !important rules in 4chan's stylesheets which have to be overridden.
