### ISSUE TITLE
Highlighting stuff

### ISSUE THREAD

**Issue by ccd0** [nebukazar/OneeChan#49]
Oneechan doesn't seem to do anything with the `filter-highlight` class except in the catalog.  And highlighting of your posts / posts quoting you only works for replies.  Also, you probably want to override what vanilla 4chan X does for `filter-highlight`.  And as of v1.10.2.0, I've added highlighting in 4chan X for your OPs / OPs quoting you, which you also probably want to override.

4chan X's highlighting stuff is here:
https://github.com/ccd0/4chan-x/blob/1.10.2.0/src/General/css/style.css#L1028
https://github.com/ccd0/4chan-x/blob/1.10.2.0/src/General/css/tomorrow.css#L50

Also, any further feedback on the way highlighting is handled in vanilla 4chan X would be welcome.

**Comment by nebukazar** [comment]
>Oneechan doesn't seem to do anything with the filter-highlight class except in the catalog.

I think I got it now. Although it should probably use its own, separate, color property and I'll have to add and pick one for every theme... I've tied it to the general highlighting for now.

>And highlighting of your posts / posts quoting you only works for replies. Also, you probably want to override what vanilla 4chan X does for filter-highlight.

It was missing `.yourPost.opContainer`, if it's not that then I don't understand what you mean here. There is no way to distinguish a thread being both watched and highlighted, right? It will get a red border in vanilla 4chan X regardless. I guess I could change the bordering style.

>Also, any further feedback on the way highlighting is handled in vanilla 4chan X would be welcome.

Hard to say since I don't use any kind of highlighting regularly and still prefer the inline 4chan catalog over the 4chan X one. I also have Oneechan enabled all the time, so my experience is not the same one as someone using only 4chan X. Just be careful with feature bloat.

**Comment by ccd0** [comment]
> It was missing .yourPost.opContainer, if it's not that then I don't understand what you mean here.

Yeah, that's what I mean.

> There is no way to distinguish a thread being both watched and highlighted, right? It will get a red border in vanilla 4chan X regardless. I guess I could change the bordering style.

That's probably a good idea for vanilla 4chan X too.  Actually, I'm thinking it was probably a mistake to change all the highlights to look the same, so I think I might release another version that uses box-shadow for `filter-highlight` again, which you may need to override in Oneechan.

**Comment by ccd0** [comment]
As of v1.10.2.1, I'm using `box-shadow` for filter-highlighting both on posts and in the catalog.
