### ISSUE TITLE
Local Mascots

### ISSUE THREAD

**Issue by lolihunter** [nebukazar/OneeChan#87]
Is there a way to import mascots from a local folder into OneeChan? I have a large collection of several hundred I have on my hard drive I want to use without the need to upload and add each individually to the userscript.

**Comment by nebukazar** [comment]
See [Links to local pages do not work](http://kb.mozillazine.org/Firefox_:_Issues_:_Links_to_Local_Pages_Don%27t_Work).

You could use a data URI generator to convert your images to base64. See [Oneechan wiki](https://github.com/nebukazar/OneeChan/wiki/Mascots#where-can-i-host-my-mascot).

**Comment by AssCrab** [comment]
I'm also thinking of switching back to OneeChan from Appchan, but the only thing keeping me from doing that is the inability to use local mascots without creating online accounts on some image services, uploading, and having to think about service failures or images getting deleted for a myriad of reasons; in addition to Appchan not being broken yet (albeit 5 months of non-updates are a bad sign).

Could you put in a visible and direct explanation on why OneeChan can't implement while Appchan can, for Firefox at least, and whether there is probability for you finding a workaround in the future which doesn't involve some conversions into 5km of image code? At least so us average Joes can understand and this topic can be given a proper informed closure.

**Comment by nebukazar** [comment]
You should read the first two links I posted above and this : https://github.com/zixaphir/appchan-x/issues/126#issuecomment-14365049

Both imgur and sli.mg don't require accounts to upload images an they support HTTPS.

>Now the 2nd big issue is why images get all distorted and destroyed depending on their width and height ratios

>increasing its size destroys the image quality and makes it blurry

If you change an image from its original size it creates noise, this noise can be attenuated by filters in programs like Photoshop but it doesn't happen in a browser. Usually when you increase the size of a complex image you're looking for information (sharpness) that isn't there to begin with, in other words an image has a native resolution at which it looks good but if you increase an image's resolution it will look blurry due to loss of quality.

>local images are for some reason automatically downscaled by Appchan

I haven't used Appchan in a while but it's probably so the images stay inside the sidebar.

**Comment by AssCrab** [comment]
Here's a visual explanation for this stuff. Words just confuse stuff:
https://i.sli.mg/zo0AKP.png
The issue is that Appchan's local mascot system precisely downscales the native resolution of the image after you have put up that base 64 stuff.
The weird thing is that it downscales it depending on the height/width ratio rather than the native resolution, and the results are varied.
So of course the blur effect happens if the native resolution has been for some reason downscaled to a stupid level and you start increasing from there. This is something that happens to often, i get mascots being downscaled even to a height of 500 pixels even though the native height is 1200 and over, but if i reduce the native width, the system suddenly becomes a little more merciful with its height downscale and maybe allows a bigger mascot of 600 or 700 pixels (or more if i'm lucky).

Frankly, this is some hilarious stuff.

Well, thanks for the info anyway. I now how ideas of what's happening. I'd still prefer no mascot than using a service though. I'm gonna move to OneeChan tonight.

**Comment by nebukazar** [comment]
I don't know what that image is about, I tried large mascots in Appchan and it works fine if you downscale them.

![capture](https://cloud.githubusercontent.com/assets/5222254/18644673/2f70422e-7ea2-11e6-906b-778d9aad9cd0.PNG)

Same mascot in Oneechan:

![capture](https://cloud.githubusercontent.com/assets/5222254/18644852/d120bde2-7ea2-11e6-92e9-6a5950c948f3.PNG)

**Comment by nebukazar** [comment]
Also technically I could add a thing to upload images but having huge images in base64 tends to slow down the browser a lot in my experience, it's best used for tiny images. I could add an option to upload theme backgrounds too but in general I want to avoid using base64. However both the mascots and themes already support base64 URIs if you introduce them.
