### ISSUE TITLE
White theme by default

### ISSUE THREAD

**Issue by hidanoki** [nebukazar/OneeChan#93]
One of the recent updates caused my theme to go from that nice dark gray to bright white. 
Is this an issue or a planned thing? 
If this is a planned thing how to I revert back to the darker theme? I looked through the options, but I couldn't find anything. Maybe I'm just blind...

**Comment by nebukazar** [comment]
I changed the default theme a couple days ago, maybe you never changed your options and that's why you now have a different theme.

Press <kbd>CTRL</kbd> + <kbd>F1</kbd> or the small gears icon in the header to access OneeChan options. Then select the Themes tab.

![capture](https://cloud.githubusercontent.com/assets/5222254/19054697/6c68eba6-89b8-11e6-893c-ddb94beb39b9.PNG)

See the wiki:
https://github.com/nebukazar/OneeChan/wiki/Custom-Themes#selecting-themes

**Comment by hidanoki** [comment]
Ah, sorry dude. Didn't even know there was a wiki.
